### ISSUE TITLE
Session 6 Report

### ISSUE THREAD

**Issue by mohammadali-seifkashani** [Sharif-OS-Lab/session-5-6#10]
Team Name: `summer1400-g3-3-97106024-96105961`

Student Name of member 1: `محمدکاظم فقیق`
Student No. of member 1: `96105961`

Student Name of member 2: `محمدعلی سیف کاشانی`
Student No. of member 2: `97106024`

- [ ] Read Session Contents.

## Section 6.4

- [ ] Using `malloc` and `free` in program
    - [ ] ![os1](https://user-images.githubusercontent.com/45390101/130636676-9790605b-a1ac-4b07-acd6-34fab98004ae.png)
    - [ ] ![os1-2](https://user-images.githubusercontent.com/45390101/130636772-3732bd65-481f-4612-b50c-a1ddfedbc713.png)

    
- [ ]  Using `ps`
    - [ ] ![os3](https://user-images.githubusercontent.com/45390101/130637822-fd4073bd-8b67-4360-8192-676f8fd8fc38.png)

F →
flags

UID →
آیدی کاربر صاحب (اجرا کننده) پردازه

PID → 
آیدی پردازه

PPID →
آیدی پردازه والد

PRI →
میزان اولویت پردازه

NI → 
nice value (اولویت پردازه در فضای کاربر)

VSZ →
اندازه حافظه مجازی اختصاص یافته به پردازه به KiB
RSS →
میزان استفاده از حافظه اصلی

WCHAN →
آدرس حافظه ی رخدادی که پردازه منتظر آن است

STAT →
کد وضعیت پردازه

TTY →
(نام) ترمینال اختصاص یافته به پردازه

TIME →
زمان اجرای CPU کلی

COMMAND →
نام پردازه که شامل آرگومان هایش هم (در صورت وجود) می باشد

- [ ]  Getting started with memory segments
    - [ ] ![os4](https://user-images.githubusercontent.com/45390101/130638134-afb387e5-126f-434d-8a2b-90fe22ef3c9c.png)
    - [ ]  ![os5](https://user-images.githubusercontent.com/45390101/130639351-0ac4a39d-469b-4667-bb74-f7ac2995bd7d.png)
    - [ ]  بخش stack, heap  را نشان نمی دهد.
    

- [ ] Getting started with memory sharing
    1. [ ] ![os6](https://user-images.githubusercontent.com/45390101/130639675-e222ef0a-c56c-441a-b637-9b6f8d44110d.png)
    1. [ ] ![os7](https://user-images.githubusercontent.com/45390101/130639804-f692b124-a9a2-4274-ada0-32a32f8cbb9b.png)
    1. [ ] ![os8](https://user-images.githubusercontent.com/45390101/130640570-367ac470-01c0-4677-bac9-c1fdbf5b16d2.png)

- [ ] Getting started with addresses
    1. [ ] خودتون گفتین چیکار میکنه. اولین آدرس بعد از بخش تکست (قسمت کد) رو خروجی میده.
    2. [ ] ![os9](https://user-images.githubusercontent.com/45390101/130641938-78736d46-90e4-4ad1-aa9e-7eddbe355bf9.png)
    2. [ ] ![os10](https://user-images.githubusercontent.com/45390101/130642282-951993da-6f09-4fac-bd27-430d57045312.png)
بله تطابق دارد.
    3. [ ] ![os11](https://user-images.githubusercontent.com/45390101/130643561-dd9eeec6-0f33-4e4e-92af-5f8e3bb31045.png)
    4. [ ] ![os12](https://user-images.githubusercontent.com/45390101/130643801-f56bf5df-f2c3-4e87-80d0-ad213c89bee5.png)
    4. [ ] ![os13](https://user-images.githubusercontent.com/45390101/130644334-c8323408-2406-4c94-9641-5f007e4c3fea.png)
    5. [ ] هربار ۴۸ واحد کم می شود.

**Comment by mhaghighat20** [comment]
100
