### ISSUE TITLE
Session 6 Report

### ISSUE THREAD

**Issue by alishaffiee** [Sharif-OS-Lab/session-5-6#11]
---
name: فرم گزارش آزمایش ششم
about: برای نوشتن گزارش آزمایشگاه از این تمپلیت استفاده کنید
title: Session 6 Report
labels: documentation
assignees: mhaghighat20

---

Team Name: `97100495-97110122`

Student Name of member 1: `علی شفیعی`
Student No. of member 1: `97110122`

Student Name of member 2: `امیر محمد قاسمی`
Student No. of member 2: `97100495`

- [ ] Read Session Contents.

# عکس‌های کامل در این لینک قرار دارند: https://github.com/Sharif-OS-Lab/summer1400-g3-3-97100495-97110122/blob/main/.github/ISSUE_TEMPLATE/session6-report-template.md

## Section 6.4

- [ ] Using `malloc` and `free` in program
    - [ ] <image src="/images/img1.png">
    - [ ] <image src="/images/img2.png">

    
- [ ]  Using `ps`
    - [ ] <image src="/images/img3.png">
    - [ ] `مقدار user نشان‌دهنده یوزری هست که پردازه را اجرا کرده است. مقدار vsz بیانگر اندازه حافظه مجازی‌ای است که این پردازه مصرف می‌کند و بر حسب کیلوبایت است. مقدار rss نشان‌دهنده مقداری از حافظه فیزیکی هست که این پردازه استفاده کرده است و در نهایت fname برابر با ۸ بایت اول نام فایل اجرایی پردازه است.`

- [ ]  Getting started with memory segments
    - [ ] `ls در آدرس /usr/bin/ls قرار دارد.`
    - [ ]  <image src="/images/img4.png">
    - [ ]  `این دستور سایز هیپ و استک را نشان نمی‌دهد.`
    

- [ ] Getting started with memory sharing
    1. [ ] <image src="/images/img5.png">
    1. [ ] <image src="/images/img6.png">
    1. [ ] <image src="/images/img7.png">

- [ ] Getting started with addresses
    1. [ ] `به کمک etext می‌توانیم اولین آدرس بعد از پایان تکست در این متغیر را پیدا کنیم و مشاهده‌های دقیق‌تر از آن در عکس‌های بعدی موجود است. مقدار این متغیر از متغیرهای دیگر کمتر است.`
    2. [ ] <image src="/images/img8.png">
    3. [ ] <image src="/images/img9.png"> <image src="/images/img10.png">
    4. [ ] <image src="/images/img11.png"> <image src="/images/img12.png">

**Comment by mhaghighat20** [comment]
100
