### ISSUE TITLE
Session 6 Report

### ISSUE THREAD

**Issue by Shayan-Shabanzadeh** [Sharif-OS-Lab/session-5-6#27]
Team Name: `97105028-98170884`

Student Name of member 1: `شایان شعبانزاده`
Student No. of member 1: `98170884`

Student Name of member 2: `علی جوان`
Student No. of member 2: `97105028`

- [ ] Read Session Contents.

## Section 6.4

- [ ] Using `malloc` and `free` in program
    - [ ] 
 ```c #include <stdio.h>
#include <stdlib.h>

struct MyStruct {
    int a;
    int b;
    char name[20];
};

int main() {
    struct MyStruct *ptr = (struct MyStruct *)malloc(sizeof(struct MyStruct));
    
    if (ptr == NULL) {
        printf("Memory allocation failed.\n");
        return 1;
    }

    // Access and initialize the members of the allocated struct
    ptr->a = 10;
    ptr->b = 20;
    snprintf(ptr->name, sizeof(ptr->name), "John");

    // Print the allocated values
    printf("a: %d\n", ptr->a);
    printf("b: %d\n", ptr->b);
    printf("name: %s\n", ptr->name);

    free(ptr);

    return 0;
}
 ```
    - [ ] `FILL HERE with screenshot of execution`

![2](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/fe959d3a-bab3-4030-831f-bd01d3a67a51)

    
- [ ]  Using `ps`
    - [ ] `FILL HERE with screenshot of command output`
![3](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/0764d755-2b54-4fdc-bbc5-d78655f82e50)

    - [ ] `FILL HERE with your descriptions (write in English or Persian)`
<div dir="rtl">
دستور man ps در ترمینال اطلاعات مربوط به دستور ps (Process Status) را نمایش می‌دهد. این اطلاعات شامل توضیحاتی درباره‌ی هر یک از ستون‌های مختلف خروجی دستور ps می‌باشد. 

    USER: نام کاربری مربوط به صاحب پردازه.

    VSZ: اندازه حافظه مجازی (Virtual Memory Size) پردازه. این ستون اندازه کل حافظه مجازی که پردازه در اختیار دارد را نشان می‌دهد (به واحد کیلوبایت).

    RSS: حافظه جاری (Resident Set Size) پردازه. این ستون نشان‌دهنده حجم حافظه‌ای است که در حالت کاری فعلی پردازه واقعاً در حافظه فیزیکی استفاده می‌شود (به واحد کیلوبایت).

    PMEM: درصد استفاده از حافظه فیزیکی توسط پردازه. این ستون نشان‌دهنده درصد حافظه فیزیکی که توسط پردازه استفاده می‌شود در مجموع حافظه فیزیکی سیستم می‌باشد.

    COMMAND یا CMD: نام دستور (فرآیند) پردازه. این ستون نشان می‌دهد که پردازه در حال اجرای چه دستوری است.

</div>

- [ ]  Getting started with memory segments
    - [ ] `FILL HERE with screenshot of which command for ls`
![4](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/dfa1432d-0365-4ece-868c-356726787f61)

    - [ ]  `FILL HERE with screenshot for size`
![5](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/2761b320-4663-4c0f-bf85-e9bead2d9524)

    - [ ]  `FILL HERE with segments not shown with size`
دستور size اطلاعاتی درباره اندازه‌های بخش‌های مختلف یک فایل اجرایی ارائه می‌دهد. بخش‌هایی که در گزارش size نمایش داده می‌شوند، عبارتند از:

    text (همچنین به عنوان code نیز شناخته می‌شود): این بخش شامل کد ماشین دستورات برنامه است.

    data (همچنین به عنوان initialized data نیز شناخته می‌شود): این بخش حاوی متغیرهای سراسری و استاتیک است که به صراحت در کد منبع مقداردهی اولیه شده‌اند.

    bss (Block Started by Symbol): این بخش حاوی متغیرهای سراسری و استاتیک است که مقداردهی نشده یا مقداردهی صفری دارند.

دستور size اطلاعاتی درباره بخش‌های زیر را گزارش نمی‌دهد:

  آدرس بالا:
 عموماً به آدرس بالای فضای حافظه در محدوده آدرس‌پذیری فرآیند اشاره دارد. این به بخشی از فایل اجرایی نیست؛ بلکه مفهومی مرتبط با نشانی‌دهی حافظه است.

  پشته (Stack): 
پشته منطقه‌ای از حافظه است که برای متغیرهای محلی و مدیریت تماس تابع استفاده می‌شود. این ساختار داده در زمان اجرا بوجود می‌آید و بخشی از فایل اجرایی نیست.

  هیپ (Heap):
 هیپ منطقه‌ای از حافظه است که برای تخصیص حافظه پویا در زمان اجرا (با استفاده از توابعی مانند malloc و free) استفاده می‌شود. همانند پشته، این یک مفهوم در زمان اجرا است و بخشی از فایل اجرایی نیست.

دستور size اطلاعاتی درباره اندازه‌های بخش‌های کد (text)، داده مقداردهی شده (data) و داده مقداردهی نشده (bss) فایل اجرایی ارائه می‌دهد. این دستور به طور مستقیم اطلاعات درباره آدرس بالا، پشته یا هیپ را ارائه نمی‌کند، زیرا این عوامل مربوط به زمان اجرا از استفاده حافظه برنامه هستند.
    

- [ ] Getting started with memory sharing
    1. [ ] `[FILL HERE with screenshot of lld for ls]`
![6](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/086e3ce3-6837-4135-95be-6fb625b9ef66)

    1. [ ] `[FILL HERE with screenshot of lld for nano]`
![7](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/e0fdb89f-69df-44ea-b952-6489ac7fb8b2)

    1. [ ] `[FILL HERE with screenshot of lld for another program]`
![Screenshot from 2023-08-11 16-52-35](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/1595ed65-aa29-4b9e-a02b-e56b008bbc5d)

- [ ] Getting started with addresses
    1. [ ] `[FILL HERE with your description about etext]`

<div dir="rtl">
اصطلاحات "etext"، "edata" و "end" برای نمایانگر مرزهای مختلف در ترکیب حافظه یک فرآیند در لینوکس استفاده می‌شوند. این اصطلاحات مرتبط با مفاهیم تقسیم بندی حافظه در سیستم‌های شباهت دار به یونیکس قدیمی هستند. با این حال، به دلیل اتخاذ یک مدل یکپارچه‌تر حافظه در برنامه‌نویسی لینوکس مدرن، این اصطلاحات در عملیات برنامه‌نویسی امروزی کمتر مورد استفاده قرار می‌گیرند.
1. "etext": به طور سنتی به پایان بخش متن (کد) اشاره دارد. این اصطلاح محلی در حافظه را نمایان می‌کند که کد اجرایی برنامه به پایان می‌رسد. در سیستم‌های مدرن، به دلیل وجود حافظه مجازی و تکنیک‌های مدیریت حافظه، مرز دقیق بین کد و داده ممکن است به اندازه سیستم‌های قدیمی مشخص نباشد.
3. "edata": به طور سنتی به پایان بخش داده‌های مقداردهی شده اشاره دارد. این اصطلاح محلی در حافظه را نمایان می‌کند که متغیرهای سراسری و استاتیکی که به صراحت در کد منبع مقداردهی اولیه شده‌اند، ذخیره می‌شوند. مانند "etext"، مرز بین داده‌های مقداردهی شده و بخش‌های دیگر ممکن است در سیستم‌های مدرن به اندازه سیستم‌های قدیمی واضح نباشد.
4. "end": به طور سنتی به پایان فضای حافظه برنامه اشاره دارد، که معمولاً بیانگر بالاترین آدرسی است که برنامه می‌تواند استفاده کند. این اصطلاح به هیچ بخش خاصی مانند کد یا داده مرتبط نیست. در سیستم‌های مدرن، مفهوم "end" به اندازه مدیریت حافظه پویا و مفهومی استفاده زیادی ندارد.
</div>

![9](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/0265691f-01f9-43e3-a35a-951b5614cbbc)

    3. [ ] `[FILL HERE with your screenshots of given program analysis]`

```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

extern char etext , edata , end;

int main(int argc, char *argv[]){
    printf("First address past:\n");
    printf("    program text (etext)    %10p\n", &etext);
    printf("    program text (edata)    %10p\n", &edata);
    printf("    program text (end)    %10p\n", &end);

    exit(EXIT_SUCCESS);
    
}
```

![10](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/d4e801cb-5e20-4599-a08d-7fa774cbddf5)

    5. [ ] `[FILL HERE with your screenshots of sbrk analysis]`
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
    void *old_brk, *new_brk;

    // Get the current end of the heap
    old_brk = sbrk(0);
    printf("Initial end of heap: %p\n", old_brk);

    // Allocate memory using malloc
    int *ptr = (int *)malloc(sizeof(int));
    if (ptr == NULL) {
        fprintf(stderr, "Memory allocation failed\n");
        return 1;
    }

    // Get the new end of the heap after malloc
    new_brk = sbrk(0);
    printf("End of heap after malloc: %p\n", new_brk);

    // Deallocate the memory
    free(ptr);

    // Get the end of the heap after freeing the memory
    new_brk = sbrk(0);
    printf("End of heap after free: %p\n", new_brk);

    return 0;
}


```

![11](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/aa6f8a0f-e20b-4319-9ee0-a5808f1e1072)

    7. [ ] `[FILL HERE with your screenshots & code of heap growth analysis]`

```c
#include <stdio.h>

void recursive_function(int depth, int *addr) {
    int i = depth;
    printf("Depth: %d, Address of i: %p\n", depth, &i);

    if (depth < 100) {
        recursive_function(depth + 1, &i);
    }
}

int main() {
    int initial_i;
    printf("Initial address of initial_i: %p\n", &initial_i);

    recursive_function(0, &initial_i);

    return 0;
}


```
![12](https://github.com/Sharif-OS-Lab/session-5-6/assets/63391129/58ac736a-239e-42ae-b5f9-b1634fa13091)

[os-6.zip](https://github.com/Sharif-OS-Lab/session-5-6/files/12322249/os-6.zip)

**Comment by shimynimi** [comment]
100
